### ISSUE TITLE
Alternative location for tmp directory

### ISSUE THREAD

**Issue by maccoylton** [rmc-team/macos-downloader#12]
**Is your feature request related to a problem? Please describe.**
Check space requirements and allow for an alternative location for the tmp directory in case where the user has insufficient space on their system disk 

**Describe the solution you'd like**
This could be either user specific or a subdirectory of the save location

**Comment by julian-fairfax** [comment]
Most users have a sufficient amount of space on their system disk. If not, that’s not an issue with macOS Downloader.
