### ISSUE TITLE
[BUG] Download not ok

### ISSUE THREAD

**Issue by det-box** [rmc-team/macos-downloader#14]
**Describe the bug**
Hello,
unfortunately the download does not work.
I have used the current zip version
The download is finished too fast, no 8GB are downloaded
In the 9 byte files there is not found
![image](https://user-images.githubusercontent.com/8150405/84591232-0c404c80-ae3d-11ea-991e-4e57784dae35.png)

**To Reproduce**
1. run the script
2. use Catalina, installer

**Screenshots/logs**
![image](https://user-images.githubusercontent.com/8150405/84590998-43adf980-ae3b-11ea-9d9a-67b93542d0a2.png)

**Mac (please complete the following information):**
 - OS: 10.15.3
 - Version [ex. 2.0]

**Additional context**
here the download folder Catalina/tmp/Install macOS Cataline
![image](https://user-images.githubusercontent.com/8150405/84591065-bd45e780-ae3b-11ea-8ec7-4a8e3288c128.png)

please check
Thanks

**Comment by julian-fairfax** [comment]
Download the latest release and try again.

**Comment by det-box** [comment]
That was the current version, I downloaded the current zip again.
Unfortunately the same. No downloads.

![image](https://user-images.githubusercontent.com/8150405/84600547-43811e80-ae7a-11ea-837e-97d3f6cc1ae3.png)

![image](https://user-images.githubusercontent.com/8150405/84600556-5693ee80-ae7a-11ea-9fd9-f76fd859ef65.png)

Sorry,
please check again
Thanks

**Comment by julian-fairfax** [comment]
Fixed!
