### ISSUE TITLE
System Support Check Failed

### ISSUE THREAD

**Issue by meaganmargaret** [rmc-team/macos-downloader#17]
Attempting to download Beta 3 of Big Sur, I get this error and it stops.

**Comment by julian-fairfax** [comment]
I need more information than just that.

**Comment by jamesst20** [comment]
@julian-fairfax 

On Big Sur beta, the following:

```
volume_version_short="$(defaults read /System/Library/CoreServices/SystemVersion.plist ProductVersion | cut -c-5)"
```

returns 11.0, so yeah it fails on line 124:

```
	if [[ $volume_version_short == "10."[7-9] || $volume_version_short == "10.1"[0-5] ]]; then
		echo -e $(date "+%b %m %H:%M:%S") ${move_up}${erase_line}${text_success}"+ System support check passed."${erase_style}
	else
		echo -e $(date "+%b %m %H:%M:%S") ${text_error}"- System support check failed."${erase_style}
		echo -e $(date "+%b %m %H:%M:%S") ${text_message}"/ Run this tool on a supported system."${erase_style}

		#Input_On
		#exit
	fi
```

**Comment by julian-fairfax** [comment]
I don't have a Mac with Big Sur so I can't test this myself. If you want to try using macOS Downloader on Big Sur, replace the first line with the second one and let me know what your results are so I can add official support for it.
`	if [[ $volume_version_short == "10."[7-9] || $volume_version_short == "10.1"[0-5] ]]; then`
`	if [[ $volume_version_short == "10."[7-9] || $volume_version_short == "10.1"[0-5] || $volume_version_short == "11.0" ]]; then`
