### ISSUE TITLE
[BUG] cant download big sur

### ISSUE THREAD

**Issue by C-r-e-a-l** [rmc-team/macos-downloader#21]
**Describe the bug**
"tar: Error opening archive: Failed to open '/tmp/Install macOS Big Sur Beta/Install macOS Big Sur Beta/Payload'**To Reproduce**"

**Screenshots/logs**
If applicable, add screenshots and/or logs to help explain your problem.
![Screen Shot 2020-11-13 at 5 56 23 PM](https://user-images.githubusercontent.com/73323444/99136447-ad445680-25d9-11eb-9470-1ba80cd8f04b.png)

**Mac (please complete the following information):**
 - OS: high sierra
 - Version 10.13.6

**Additional context**
cant download big sur

**Comment by julian-fairfax** [comment]
Fixed

**Comment by Franky1971** [comment]
Same problem
![Bildschirmfoto 2020-11-15 um 13 21 37](https://user-images.githubusercontent.com/72747399/99388191-7c179f00-28d5-11eb-9d85-44584a53c1aa.png)

**Comment by yorkyang19048** [comment]
> Same problem
> ![Bildschirmfoto 2020-11-15 um 13 21 37](https://user-images.githubusercontent.com/72747399/99388191-7c179f00-28d5-11eb-9d85-44584a53c1aa.png)

I am having the same problem too, using the latest version 
![Screenshot 2020-11-17 at 18 50 21](https://user-images.githubusercontent.com/65583617/99434003-30c9b480-2906-11eb-95d4-757f400ba57c.png)

**Comment by julian-fairfax** [comment]
I know it's an unsatisfying answer but it works fine for me so I'm not sure what the problem is. Could one of you run it with -v and send me the full output so I can take better look and what's happening?

**Comment by yorkyang19048** [comment]
@julian-fairfax  thank you for your reply. Can you elaborate on how to do it please.

**Comment by Franky1971** [comment]
Du you mean that?
macOS Download.sh -v
![Bildschirmfoto 2020-11-17 um 20 04 56](https://user-images.githubusercontent.com/72747399/99435506-7ee3b580-2910-11eb-98e1-351d9fffff7a.png)

**Comment by Franky1971** [comment]
Sorry.. Downloader.sh -v

**Comment by julian-fairfax** [comment]
I need to see the downloading process. Could you please try downloading the big sur installer with -v and send me the output?

**Comment by C-r-e-a-l** [comment]
I tried again and it said “downloading” for 5 hours. nothing in the folder at all. :(

**Comment by yorkyang19048** [comment]
@julian-fairfax Here's the full output, thanks. 
[Terminal Saved Output.zip](https://github.com/rmc-team/macos-downloader/files/5555936/Terminal.Saved.Output.zip)

**Comment by julian-fairfax** [comment]
Thanks! I'll see if I can test this on Catalina, as I use personally Mojave.

**Comment by yorkyang19048** [comment]
Thank you so much. I'll try it on Mojave later and see if it works.

**Comment by yorkyang19048** [comment]
Worked on Mojave

**Comment by julian-fairfax** [comment]
Hmm, that's odd. I'll revert the changes I made later, but this was faster so it's a shame

**Comment by julian-fairfax** [comment]
Could someone download [this version](https://github.com/rmc-team/macos-downloader/archive/master.zip) and try it?

**Comment by C-r-e-a-l** [comment]
Sure. Btw the downloader worked w/ -V but only got a 8XX something MB installer... on high sierra

**Comment by Franky1971** [comment]
Works perfectly. Thank you. Are you also making a Patcher this time? :)?

**Comment by C-r-e-a-l** [comment]
> Works perfectly. Thank you. Are you also making a Patcher this time? :)?

You’d have no graphics acceleration which basically means resizing a window could take up to a minute.. not worth it, just upgrade

**Comment by codethought** [comment]
As of today this is not working for me.. and I tried the one @julian-fairfax referenced on the 18th.

I've captured the paste here: 

https://pastebin.com/B18G2mK6

Basically the following curl command doesn't give an error, but it's also not fetching anything either

`curl --cacert /Users/codethought/Downloads/macos-downloader//resources/cacert.pem -L -s -o '/tmp/Install macOS Big Sur/Install macOS Big Sur.pkg' http://swcdn.apple.com/content/downloads/50/49/001-79699-A_93OMDU5KFG/dkjnjkq9eax1n2wpf8rik5agns2z43ikqu/InstallAssistant.pkg`

**Comment by julian-fairfax** [comment]
This should be fixed now but I'm sure for how much longer I'll update the catalog. Thanks for reminding me!
