### ISSUE TITLE
macOS Downloader not working on macOS Big Sur 11.1

### ISSUE THREAD

**Issue by seyoon20087** [rmc-team/macos-downloader#23]
macOS Downloader is not working on macOS Big Sur 11.1 and returning this:
```
> Checking system support.
- System support check failed.
/ Run this tool on a supported system.
```
CAN YOU PLEASE FIX THIS?

Operating system : macOS Big Sur 11.1 (20C69)
Model : iMac (21.5-inch, 2017)
Processor : 2.3 GHz Dual-Core Intel Core i5
Memory : 8 GB 2133 MHz DDR4
Graphics : Intel Iris Plus Graphics 640 1536 MB

**Comment by julian-fairfax** [comment]
Hi, could you download [this version](https://github.com/rmc-team/macos-downloader/archive/master.zip) and try it? Thank you!

**Comment by seyoon20087** [comment]
YES !!  It worked!

BTW: Actually I did `git clone` to clone this and run the downloader at the first time.

**Comment by MikeBeaton** [comment]
I just downloaded the current release from releases on Big Sur 11.2 RC 2 and am getting the same error. Also tried downloading directly with git - current master branch - same result.

**Comment by julian-fairfax** [comment]
Ok, I just pushed a potential fix that will check if the short version number is 4 characters (11.0, 11.1, 11.2, etc) then shorten it to 2 characters (11), and just check if the short version number is 11.

**Comment by MikeBeaton** [comment]
Thanks, I can confirm that that now passes the support check on my 11.2 system.
