### ISSUE TITLE
[BUG] Run this tool on a supported system.

### ISSUE THREAD

**Issue by wstroftgithub** [rmc-team/macos-downloader#26]
Checking system support.
System support check failed.
Run this tool on a supported system.

 - OS: OSX 10.6.8

**Comment by julian-fairfax** [comment]
Oh yeah forgot to mention, macOS Downloader isn't only supported on Lion and up. Your best bet is to upgrade to Lion, then go from there.

**Comment by seyoon20087** [comment]
Try out my [fork](https://github.com/seyoon20087/macos-downloader); it's also designed for Mac OS X Snow Leopard (untested).

**Comment by julian-fairfax** [comment]
Feel free to try it but it won't work on Snow Leopard for a reason so changing the version check won't fix that

Sent from ProtonMail mobile

-------- Original Message --------
