### ISSUE TITLE
Resources check failed

### ISSUE THREAD

**Issue by TerrorSource** [rmc-team/macos-downloader#4]
sudo sh macOS\ Downloader.sh 
+ Checked system environment.
+ Root permissions check passed.
> Checking for resources.
- Resources check failed.
/ Run this tool with the required resources.

**Comment by seyoon20087** [comment]
You have only downloaded `macOS Downloader.sh`.

macOS Downloader requires additional resources to run the downloader.

Consider proceeding one of the following tasks:

- If you have access to Xcode or Xcode Command Line Tools, try typing `git clone https://github.com/rmc-team/macos-downloader.git`
- If not, please clone the code using:
![image](https://user-images.githubusercontent.com/24852454/108026969-bc212600-706c-11eb-860c-8927e9c30a5e.png)
- Or you can download from the [releases page](https://github.com/rmc-team/macos-downloader/releases/latest).
