### ISSUE TITLE
Downloader fails on MacOS 10.7

### ISSUE THREAD

**Issue by johnmanko** [rmc-team/macos-downloader#8]
I changed the curl command to use flag `-S` to show errors.  This will bite people trying to run this script on MacOS 10.7.

```shell
$ sudo /Users/johnmanko/Downloads/macos-downloader-master/macOS\ Downloader.sh 
Password:
+ Checked system environment.
+ Root permissions check passed.
+ Resources check passed.
+ Integrity conectivity check passed.
/ What save folder would you like to use?
/ Input a save folder path.
/ /Users/johnmanko/Downloads/installers
+ Write permissions check passed.
/ What operation would you like to run?
/ Input an operation number.
/     1 - Catalina
/     2 - Mojave
/     3 - High Sierra
/     4 - Sierra
/     5 - El Capitan
/     6 - Yosemite
/ 2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
chmod: /tmp/Catalog.sh: No such file or directory
/Users/johnmanko/Downloads/macos-downloader-master/macOS Downloader.sh: line 221: /tmp/Catalog.sh: No such file or directory
chmod: /tmp//Catalog.sh: No such file or directory
/Users/johnmanko/Downloads/macos-downloader-master/macOS Downloader.sh: line 286: /tmp//Catalog.sh: No such file or directory
/ What operation would you like to run?
/ Input an operation number.
/     1 - Installer
```

```shell
$ curl --version
curl 7.21.4 (universal-apple-darwin11.0) libcurl/7.21.4 OpenSSL/0.9.8z zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IPv6 Largefile NTLM SSL libz
```

**Comment by julian-fairfax** [comment]
This seems to be due to the SSL implementation in Lion's default curl. I also faced this when accessing the GitHub page in Safari. You can get around this be installing MacPorts and then curl from there. You also have to change the path to the curl binary in the script. This solves the first problem. 

The second problem, which I discovered after installing and using the newer curl version, is that pbzx doens't seem to work on 10.7. I'm not sure what the minimum requirements are for that, but there's not much I can do. I'm sorry about the situation. I'm leaving this open and I'll try my best to assist you with anything else.

**Comment by julian-fairfax** [comment]
A little update on this, installing Xcode Command Line Tools, MacPorts, and then installing curl from MacPorts, will get you a working version. I don't have source code for his changes but dosdude1 built a working version of pbzx for Lion and maybe even older. I can release this version, but three steps just to get it to work on Lion is probably annoying for most. What's your take? I can send you a test build too if you'd like.

**Comment by johnmanko** [comment]
I was able to borrow a newer mac to get this working, but macports seems like a viable option for others.  Thanks for the effort, though.
